### ISSUE TITLE
panic: Got an unexpected response. Wanted 0x02 got 3

### ISSUE THREAD

**Issue by kokxxoo** [C-Sto/goWMIExec#4]
1.6167636056505682e+09	info	wmiexec/wmiexec.go:176	Successfully connected to host and sent an RPC request packet
panic: Got an unexpected response. Wanted 0x02 got 3

goroutine 1 [running]:
main.main()
	/home/runner/work/goWMIExec/src/github.com/C-Sto/goWMIExec/main.go:43 +0x65c

**Comment by C-Sto** [comment]
That response type is a generic error, if I can't reproduce it locally this is going to be very difficult to fix

**Comment by C-Sto** [comment]
(ref 12.1 page 575)
https://pubs.opengroup.org/onlinepubs/9629399/toc.pdf
